### ISSUE TITLE
Optimizing spring boot autoprompts

### ISSUE THREAD

**Issue by guoshiqiufeng** [guoshiqiufeng/loki#7]
Optimizing spring boot autoprompts

e.g.
```yml
loki:
  global-config:
    mq-config:
      mq-type: ROCKET_MQ
      
```
